/**
 * reminder-engine v4.1 — 提醒规则引擎 (PRD v3.1)
 * V5升级: 12×4×N四维规则矩阵 + 置信度分级 + 决策节点提醒
 */
const cloud = require('wx-server-sdk');
cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV });
const db = cloud.database();
const _ = db.command;

// V5置信度规则: A/B自动生效, C需确认, D不自动生成
const AUTO_APPLY = ['A', 'B'];
const CONFIRM_APPLY = ['C'];
const DISABLED_APPLY = ['D'];

exports.main = async (event) => {
  const { action } = event;
  const wxContext = cloud.getWXContext();
  const openid = wxContext.OPENID;
  try {
    switch (action) {
      case 'generateFromEvent':  return await generateFromEvent(openid, event);
      case 'generateFromOCR':    return await generateFromOCR(openid, event.docId);
      case 'generateFromText':   return await generateFromText(openid, event.text);
      case 'createCustom':       return await createCustom(openid, event);
      case 'confirm':            return await confirmReminder(openid, event.reminderIds);
      case 'dismiss':            return await dismissReminder(openid, event);
      case 'complete':           return await completeReminder(openid, event.reminderId);
      case 'listActive':         return await listActive(openid);
      case 'listByDate':         return await listByDate(openid, event);
      case 'getByProcess':       return await getByProcess(openid, event.processId);
      case 'getTimeline':        return await getTimeline(openid, event.processId);
      case 'scanExpiringToday':  return await scanExpiringToday();
      case 'getRule':            return await getRule(event.ruleId);
      case 'getDecisionReminders': return await getDecisionReminders(openid, event.decisionPoint);
      default:                   return { code: 400, msg: '无效操作' };
    }
  } catch (err) {
    console.error('[reminder-engine]', err);
    return { code: 500, msg: '提醒服务异常', error: err.message };
  }
};

async function generateFromEvent(openid, event) {
  const { eventName, eventDate, pathType, phase, docId } = event;
  if (!eventName || !eventDate) return { code: 400, msg: '缺少事件名或日期' };

  const rulesQuery = { isActive: true };
  if (pathType) rulesQuery['trigger.pathType'] = _.in([pathType, 'all']);
  if (phase) rulesQuery['trigger.phase'] = phase;
  const rulesResult = await db.collection('reminder_rules').where(rulesQuery).get();

  const matchedRules = rulesResult.data.filter(r => {
    const te = (r.trigger.event || '').toLowerCase();
    const en = eventName.toLowerCase();
    return te.includes(en) || en.includes(te);
  });

  if (matchedRules.length === 0) return { code: 0, data: { reminders: [], ruleCount: 0, message: '未找到匹配规则' } };

  const generated = [];
  for (const rule of matchedRules) {
    // V5置信度过滤: D级不自动生成
    if (DISABLED_APPLY.includes(rule.confidence)) continue;
    const autoApply = AUTO_APPLY.includes(rule.confidence) ? 'auto' : CONFIRM_APPLY.includes(rule.confidence) ? 'confirm' : 'auto';

    for (const rem of rule.reminders || []) {
      const deadlineDate = calcDeadline(eventDate, rem.offsetDays);
      const alertDates = calcAlertDates(deadlineDate, rem.alerts || []);
      generated.push({
        _openid: openid, ruleId: rule.ruleId, sourceDocId: docId || null,
        title: rem.label, description: rem.description || '',
        baselineDate: eventDate, deadlineDate, alertDates,
        parentReminderId: null, childReminderIds: [],
        status: autoApply === 'confirm' ? 'pending_confirm' : 'pending',
        // V5新增字段
        confidence: rule.confidence || 'B',
        autoApply, path: rule.path || null, phase: rule.phase || null,
        decisionPoint: rule.milestone_tag || null, legalBasis: rule.legal_basis || null,
        completedAt: null, dismissedAt: null, dismissedReason: null,
        lastNotifiedAt: null, notifyCount: 0, notifyChannel: 'subscription_msg',
        isCustom: false, isAutoGenerated: true,
        createdAt: db.serverDate(), updatedAt: db.serverDate()
      });
    }
  }
  return { code: 0, data: { eventName, eventDate, candidates: generated, totalCount: generated.length } };
}

async function generateFromOCR(openid, docId) {
  if (!docId) return { code: 400, msg: '缺少 docId' };
  const doc = await db.collection('user_documents').where({ _id: docId, _openid: openid }).get();
  if (doc.data.length === 0) return { code: 404, msg: '证件不存在' };
  const record = doc.data[0];
  const dates = [];
  const fields = record.ocrResult?.fields || {};
  if (fields.validFrom) dates.push({ label: '生效日期', date: fields.validFrom, field: 'validFrom' });
  if (fields.validUntil) dates.push({ label: '有效截止', date: fields.validUntil, field: 'validUntil' });
  if (fields.birthDate) dates.push({ label: '出生日期', date: fields.birthDate, field: 'birthDate' });
  const allCandidates = [];
  for (const d of dates) {
    const result = await generateFromEvent(openid, { eventName: `${record.docName}${d.label}`, eventDate: d.date, docId });
    if (result.code === 0 && result.data.candidates) allCandidates.push(...result.data.candidates);
  }
  return { code: 0, data: { docId, docName: record.docName, detectedDates: dates, candidates: allCandidates } };
}

async function generateFromText(openid, text) {
  if (!text) return { code: 400, msg: '文本为空' };
  const datePatterns = [/(\d{4})[年\-\/](\d{1,2})[月\-\/](\d{1,2})/g, /(\d{4})-(\d{2})-(\d{2})/g, /(\d{4})\/(\d{2})\/(\d{2})/g];
  const detectedDates = [];
  for (const p of datePatterns) {
    let m;
    while ((m = p.exec(text)) !== null) {
      const ds = `${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;
      if (!detectedDates.find(dd => dd.date === ds)) detectedDates.push({ date: ds, context: m[0] });
    }
  }
  const allCandidates = [];
  for (const dd of detectedDates) {
    const r = await generateFromEvent(openid, { eventName: '文本提取日期', eventDate: dd.date });
    if (r.code === 0 && r.data.candidates) allCandidates.push(...r.data.candidates);
  }
  return { code: 0, data: { detectedDates, candidates: allCandidates } };
}

async function confirmReminder(openid, reminderIds) {
  const ids = Array.isArray(reminderIds) ? reminderIds : [reminderIds];
  const confirmed = [];
  for (const rid of ids) {
    if (typeof rid === 'object') {
      delete rid._dependsOn; delete rid._ruleIndex;
      rid.status = 'pending'; rid.createdAt = db.serverDate(); rid.updatedAt = db.serverDate();
      const r = await db.collection('user_reminders').add({ data: rid });
      confirmed.push(r._id);
    } else {
      await db.collection('user_reminders').where({ _id: rid, _openid: openid }).update({ data: { status: 'pending', updatedAt: db.serverDate() } });
      confirmed.push(rid);
    }
  }
  await activateChainChildren(openid, confirmed);
  await db.collection('users').where({ _openid: openid }).update({ data: { reminderCount: _.inc(confirmed.length), updatedAt: db.serverDate() } });
  return { code: 0, data: { confirmedIds: confirmed } };
}

async function createCustom(openid, event) {
  const { title, description, baselineDate, deadlineDate, alertDays } = event;
  if (!title || !deadlineDate) return { code: 400, msg: '缺少标题或截止日期' };
  const alerts = alertDays || [30, 14, 7, 3, 1];
  const alertDates = calcAlertDates(deadlineDate, alerts);
  const r = await db.collection('user_reminders').add({ data: { _openid: openid, ruleId: null, sourceDocId: event.docId || null, title, description: description || '', baselineDate: baselineDate || new Date().toISOString().slice(0,10), deadlineDate, alertDates, parentReminderId: null, childReminderIds: [], status: 'pending', isCustom: true, isAutoGenerated: false, notifyChannel: event.notifyChannel || 'subscription_msg', createdAt: db.serverDate(), updatedAt: db.serverDate() } });
  return { code: 0, data: { reminderId: r._id } };
}

async function dismissReminder(openid, event) {
  const { reminderId, reason } = event;
  await db.collection('user_reminders').where({ _id: reminderId, _openid: openid }).update({ data: { status: 'dismissed', dismissedAt: db.serverDate(), dismissedReason: reason || '' } });
  return { code: 0, msg: 'ok' };
}

async function completeReminder(openid, reminderId) {
  await db.collection('user_reminders').where({ _id: reminderId, _openid: openid }).update({ data: { status: 'completed', completedAt: db.serverDate() } });
  await activateChainChildren(openid, [reminderId]);
  return { code: 0, msg: 'ok' };
}

async function listActive(openid) {
  const r = await db.collection('user_reminders').where({ _openid: openid, status: _.in(['pending', 'pending_confirm']) }).orderBy('deadlineDate', 'asc').get();
  return { code: 0, data: groupByDate(r.data) };
}

async function listByDate(openid, event) {
  const { range = 'all' } = event || {};
  const now = new Date(); let dateFilter;
  if (range === 'today') { dateFilter = { alertDates: now.toISOString().slice(0,10) }; }
  else if (range === 'week') { const we = new Date(now.getTime()+7*86400000).toISOString().slice(0,10); dateFilter = { alertDates: _.elemMatch(_.gte(now.toISOString().slice(0,10)).and(_.lte(we))) }; }
  const query = { _openid: openid, status: 'pending' }; if (dateFilter) Object.assign(query, dateFilter);
  const r = await db.collection('user_reminders').where(query).orderBy('deadlineDate', 'asc').get();
  return { code: 0, data: r.data };
}

async function getByProcess(openid, processId) {
  const docs = await db.collection('user_documents').where({ _openid: openid }).get();
  const docIds = docs.data.map(d => d._id);
  const r = await db.collection('user_reminders').where({ _openid: openid, sourceDocId: _.in(docIds) }).orderBy('deadlineDate', 'asc').get();
  return { code: 0, data: r.data };
}

async function getTimeline(openid, processId) {
  const all = await db.collection('user_reminders').where({ _openid: openid }).orderBy('deadlineDate', 'asc').get();
  const nodes = all.data.map(r => ({ id: r._id, title: r.title, baselineDate: r.baselineDate, deadlineDate: r.deadlineDate, status: r.status, isCompleted: r.status==='completed', isOverdue: r.status==='pending'&&new Date(r.deadlineDate)<new Date(), isUpcoming: r.status==='pending'&&daysUntil(r.deadlineDate)<=7, confidence: r.confidence, decisionPoint: r.decisionPoint }));
  const total = nodes.length, completed = nodes.filter(n=>n.isCompleted).length;
  return { code: 0, data: { nodes, progress: total>0?Math.round(completed/total*100):0, total, completed } };
}

async function scanExpiringToday() {
  // 仅允许定时触发器调用——无openid上下文时执行全量扫描
  // 如有调用方openid（用户直接调用），则过滤到该用户
  var wxContext;
  try { wxContext = cloud.getWXContext(); } catch(e) {}
  var openid = wxContext ? wxContext.OPENID : null;
  var today = new Date().toISOString().slice(0,10);
  var query = { status: 'pending', alertDates: _.elemMatch(_.lte(today)) };
  if (openid) query._openid = openid;
  var r = await db.collection('user_reminders').where(query).limit(openid ? 50 : 500).get();
  var expiring = r.data.filter(function(rem) { var ld = rem.lastNotifiedAt ? new Date(rem.lastNotifiedAt).toISOString().slice(0,10) : null; return ld !== today; });
  // 如果有openid上下文，脱敏返回（不暴露其他用户数据）
  if (openid) {
    return { code: 0, data: { expiringCount: expiring.length, expiringReminders: expiring } };
  }
  return { code: 0, data: { expiringCount: expiring.length } };
}

async function getRule(ruleId) {
  const r = await db.collection('reminder_rules').where({ ruleId }).get();
  if (r.data.length === 0) return { code: 404, msg: '规则不存在' };
  return { code: 0, data: r.data[0] };
}

// V5新增: 决策节点提醒
async function getDecisionReminders(openid, decisionPoint) {
  const r = await db.collection('user_reminders').where({ _openid: openid, decisionPoint, status: _.in(['pending', 'pending_confirm']) }).orderBy('deadlineDate', 'asc').get();
  return { code: 0, data: r.data || [] };
}

// 辅助函数
function calcDeadline(d, o) { const b = new Date(d); b.setDate(b.getDate()+o); return b.toISOString().slice(0,10); }
function calcAlertDates(dl, offsets) { const deadline = new Date(dl), now = new Date(); return offsets.map(d => { const a = new Date(deadline.getTime()-d*86400000); return a.toISOString().slice(0,10); }).filter(d => new Date(d) >= new Date(now.toISOString().slice(0,10))); }
function daysUntil(d) { return Math.ceil((new Date(d).getTime()-Date.now())/86400000); }
function groupByDate(reminders) {
  const g = { overdue: [], today: [], week: [], month: [], later: [] };
  const now = new Date(), today = now.toISOString().slice(0,10), we = new Date(now.getTime()+7*86400000).toISOString().slice(0,10), me = new Date(now.getTime()+30*86400000).toISOString().slice(0,10);
  for (const r of reminders) { if (r.deadlineDate<today) g.overdue.push(r); else if (r.deadlineDate===today) g.today.push(r); else if (r.deadlineDate<=we) g.week.push(r); else if (r.deadlineDate<=me) g.month.push(r); else g.later.push(r); }
  return g;
}
async function activateChainChildren(openid, parentIds) {
  for (const pid of parentIds) {
    const parent = await db.collection('user_reminders').where({ _id: pid, _openid: openid }).get();
    if (parent.data.length === 0) continue;
    const ruleId = parent.data[0].ruleId; if (!ruleId) continue;
    const rule = await db.collection('reminder_rules').where({ ruleId }).get();
    if (rule.data.length === 0) continue;
    for (const rem of rule.data[0].reminders || []) {
      if (!rem.dependsOn) continue;
      const children = await db.collection('user_reminders').where({ _openid: openid, ruleId, status: 'chain_waiting' }).get();
      for (const child of children.data) {
        const gen = await generateFromEvent(openid, { eventName: '链式触发', eventDate: parent.data[0].deadlineDate });
        if (gen.code===0&&gen.data.candidates) {
          for (const cand of gen.data.candidates) {
            if (cand.title===rem.label) { cand.parentReminderId=pid; cand.status='pending'; delete cand._dependsOn; const s=await db.collection('user_reminders').add({data:cand}); await db.collection('user_reminders').where({_id:pid}).update({data:{childReminderIds:_.push(s._id)}}); }
          }
        }
      }
    }
  }
}
