/**
 * free-trial-monitor — 免费试用监控云函数
 * 定时扫描：试用到期锁定、到期前提醒推送
 *
 * PRD v3 覆盖: FL-01~FL-03
 * 触发器：建议每日 00:05
 */
const cloud = require('wx-server-sdk');
cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV });
const db = cloud.database();
const _ = db.command;

exports.main = async (event, context) => {
  const { action = 'dailyCheck' } = event || {};

  try {
    switch (action) {
      case 'dailyCheck':     return await dailyCheck();
      case 'checkUser':      return await checkUser(event.openid);
      case 'getStatus':      return await getTrialStatus(event.openid);
      default:               return await dailyCheck();
    }
  } catch (err) {
    console.error('[free-trial-monitor]', err);
    return { code: 500, msg: '试用监控异常', error: err.message };
  }
};

/**
 * 每日定时检查
 * FL-01: 到期锁定  FL-02: 到期前提醒
 */
async function dailyCheck() {
  const now = new Date();
  const today = now.toISOString().slice(0, 10);
  const stats = { locked: 0, warned: 0, alreadyLocked: 0 };

  // 1. 查找今天到期的免费试用用户
  const expiringToday = await db.collection('users')
    .where({
      membershipLevel: 'free_trial',
      isLocked: false,
      freeTrialEndAt: _.lte(today + 'T23:59:59.999Z')
    }).limit(500).get();

  for (const user of expiringToday.data) {
    await _lockUser(user._openid);
    stats.locked++;
  }

  // 2. 查找应在今天收到提醒的用户（30/14/7/3/1天前）
  const warningDays = [30, 14, 7, 3, 1];
  for (const days of warningDays) {
    const warnDate = new Date(now.getTime() + days * 86400000);
    const warnDateStr = warnDate.toISOString().slice(0, 10);

    const usersToWarn = await db.collection('users')
      .where({
        membershipLevel: 'free_trial',
        isLocked: false,
        freeTrialEndAt: _.gte(warnDateStr + 'T00:00:00.000Z')
          .and(_.lte(warnDateStr + 'T23:59:59.999Z'))
      }).get();

    for (const user of usersToWarn.data) {
      await _createTrialExpiryReminder(user._openid, user.freeTrialEndAt, days);
      stats.warned++;
    }
  }

  // 3. 统计已锁定的用户（确认）
  const alreadyLocked = await db.collection('users')
    .where({ isLocked: true }).count();
  stats.alreadyLocked = alreadyLocked.total;

  return {
    code: 0, msg: 'ok',
    data: { checkedAt: today, ...stats }
  };
}

/**
 * 检查单个用户试用状态
 */
async function checkUser(openid) {
  const result = await db.collection('users')
    .where({ _openid: openid }).limit(1).get();
  if (result.data.length === 0) return { code: 404, msg: '用户不存在' };

  const user = result.data[0];
  if (user.membershipLevel !== 'free_trial' || user.isLocked) {
    return { code: 0, data: { locked: user.isLocked, trialExpired: true } };
  }

  const now = new Date();
  const endDate = new Date(user.freeTrialEndAt);
  const daysRemaining = Math.ceil((endDate.getTime() - now.getTime()) / 86400000);

  if (daysRemaining <= 0) {
    await _lockUser(openid);
    return { code: 0, data: { locked: true, trialExpired: true } };
  }

  return {
    code: 0,
    data: { locked: false, trialExpired: false, daysRemaining, freeTrialEndAt: user.freeTrialEndAt }
  };
}

/**
 * 获取用户试用状态
 */
async function getTrialStatus(openid) {
  const result = await db.collection('users')
    .where({ _openid: openid }).limit(1).get();
  if (result.data.length === 0) return { code: 404, msg: '用户不存在' };

  const user = result.data[0];
  const now = new Date();
  const endDate = new Date(user.freeTrialEndAt);
  const daysRemaining = Math.ceil((endDate.getTime() - now.getTime()) / 86400000);

  return {
    code: 0,
    data: {
      membershipLevel: user.membershipLevel,
      isLocked: user.isLocked || false,
      freeTrialStartAt: user.freeTrialStartAt,
      freeTrialEndAt: user.freeTrialEndAt,
      daysRemaining: Math.max(0, daysRemaining),
      trialExpired: daysRemaining <= 0 && user.membershipLevel === 'free_trial'
    }
  };
}

// ========== 内部函数 ==========

/**
 * FL-01: 锁定用户
 */
async function _lockUser(openid) {
  await db.collection('users')
    .where({ _openid: openid })
    .update({
      data: { isLocked: true, updatedAt: db.serverDate() }
    });

  await db.collection('audit_logs').add({
    data: {
      _openid: openid,
      action: 'trial_expired',
      detail: { entityType: 'user', entityId: openid, toState: 'locked' },
      createdAt: db.serverDate()
    }
  });
}

/**
 * FL-02: 创建到期提醒
 */
async function _createTrialExpiryReminder(openid, endDate, daysRemaining) {
  // 检查是否已创建过相同天数的提醒
  const existing = await db.collection('user_reminders')
    .where({
      _openid: openid,
      title: `免费试用即将到期`,
      deadlineDate: endDate,
      isAutoGenerated: true
    }).count();

  if (existing.total > 0) return;

  await db.collection('user_reminders').add({
    data: {
      _openid: openid,
      ruleId: 'R_TRIAL_EXPIRY',
      sourceDocId: null,
      title: '免费试用即将到期',
      description: `您的免费试用将在${daysRemaining}天后到期，到期后全部功能将锁定。请及时续费以保持服务。`,
      baselineDate: new Date().toISOString().slice(0, 10),
      deadlineDate: endDate,
      alertDates: [new Date().toISOString().slice(0, 10)],
      status: 'pending',
      notifyChannel: 'subscription_msg',
      isCustom: false,
      isAutoGenerated: true,
      createdAt: db.serverDate(),
      updatedAt: db.serverDate()
    }
  });
}
